print("You can write any R code and package it into a container")
print("Including your favorite packages")
print("It will then run on the cloud")
print("You can submit as many jobs as you like")
print("And tear down the infrastructure after its finished")
print("So that you can safe some money :)")

print(sum(5,5))
print(sum(5,4))
print(sum(5,3))
print(sum(5,2))
print(sum(5,1))
print(sum(3,2))
print(sum(3,1))
print(sum(2,1))
print(sum(1,1))
print(sum(1,0))
print(sum(0,0))

print("Bye!!!!!")